#!/bin/sh

id=`id | cut -f1 -d'('`
if [ $id != "uid=0" ]
then
	echo
	echo "You must be root to run this script"
	echo
	exit
fi

if [ "$1" = "test" ]
then
	./test/setup.sh
fi

useradd -s /sbin/nologin -d /nonexistent _aaa

rm -rf passwords
mkdir passwords

touch passwords/auth.db.password
touch passwords/admin.db.password

#------- Passwords for various operations -----------

touch passwords/update_crl.db.password

#----------------------------------------------------

chmod 400 passwords/*

for f in `ls passwords`
do
	head /dev/urandom | sha256sum | awk '{ print $1 }' > passwords/$f 

	password=`cat passwords/$f`
	label=`echo $f | cut -f1 -d'.'`

	sed -i "s/XXX_$label/$password/" schema.sql 
done

# move admin file
mv admins.json passwords/

# copy files to passwords/ for CSR signing
if [ ! -f cert.pem ]; then
	openssl req -x509 -nodes -days 365 -subj "/CN=ca.iudx.org.in/emailAddress=ca@iudx.org.in" -newkey rsa:2048 -keyout key.pem -out cert.pem
fi

mv cert.pem key.pem passwords/

echo your-telegram-api-key		> telegram.apikey
echo your-telegram-chat-id		> telegram.chatid

chmod 400 telegram.*
chmod 400 *.sql

apt update
apt upgrade -y

# setup postgresql
apt install -y postgresql postgresql-contrib
apt install -y libpq-dev

# TODO : change 12
until pg_isready
do
	pg_ctlcluster 12 main start
	sleep 1
done

chmod u+x setup.postgresql.ubuntu
./setup.postgresql.ubuntu

# local setup

touch https-key.pem
chmod 400 https-key.pem

openssl req -x509 -nodes -days 365 -subj "/CN=auth.iudx.org.in" -newkey rsa:2048 -keyout https-key.pem -out https-certificate.pem

apt install -y nodejs npm nginx
apt install -y certbot python3-certbot-nginx

# nginx config
#
# nginx allows for only one ssl_client_certificate parameter
# so the system ca-certificates.crt (to allow lets encrypt certs)
# must be concatenated with the other .crt files

# We also add the `cert.pem` file to allow any certificates signed by it
# to be accepted by NGINX

# TODO: Other way to do it would be to move the .crt files to /etc/ssl/certs
# directory, then run 'update-ca-certificates'. nginx will use the
# /etc/certs/ca-certificates.crt file directly

mkdir /etc/nginx/certs
cat /etc/ssl/certs/ca-certificates.crt ca.iudx.org.in.crt passwords/cert.pem CCAIndia2014.cer CCAIndia2015.cer > ca-certs.crt
cp ca-certs.crt /etc/nginx/certs/

source certbot.env

cp nginx.conf /etc/nginx/sites-available/$AUTH_DOMAIN
sed -i "s/AUTH_DOMAIN/$AUTH_DOMAIN/" /etc/nginx/sites-available/$AUTH_DOMAIN
ln -s /etc/nginx/sites-available/$AUTH_DOMAIN /etc/nginx/sites-enabled/
certbot --nginx --non-interactive --agree-tos -m $EMAIL -d $AUTH_DOMAIN --test-cert

cp consent-nginx.conf /etc/nginx/sites-available/$CONSENT_DOMAIN
sed -i "s/CONSENT_DOMAIN/$CONSENT_DOMAIN/" /etc/nginx/sites-available/$CONSENT_DOMAIN
ln -s /etc/nginx/sites-available/$CONSENT_DOMAIN /etc/nginx/sites-enabled/
certbot --nginx --non-interactive --agree-tos -m $EMAIL -d $CONSENT_DOMAIN --test-cert

systemctl restart nginx

i=`systemctl is-active nginx`

if [ $i != "active" ]
then
	echo
	echo "nginx not running!!"
	echo
	exit
fi

git clone --depth=1 https://github.com/rbccps-iisc/node-aperture
cd node-aperture
npm install
npm audit fix --force

cd ..
npm install
npm audit fix --force

	until pg_isready -h 127.0.0.1
	do
		sleep 1
	done

cp auth-server.service /etc/systemd/system
systemctl daemon-reload
systemctl enable auth-server.service
systemctl start auth-server.service

cp crl-script.service /etc/systemd/system
systemctl daemon-reload
systemctl enable crl-script.service
systemctl start crl-script.service

i=`systemctl is-active auth-server`

if [ $i != "active" ]
then
	echo
	echo "Auth server not running!!"
	echo
	exit
fi

i=`systemctl is-active crl-script`

if [ $i != "active" ]
then
	echo
	echo "CRL script not running!!"
	echo
	exit
fi
